ideascube/monitoring/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^entry/$', views.entry, name='entry'),
    url(r'^entry/export/$', views.export_entry, name='export_entry'),
    url(r'^stock/$', views.stock, name='stock'),
    url(r'^stock/export/$', views.stock_export, name='stock_export'),
    url(r'^stock/import/$', views.stock_import, name='stock_import'),
    url(r'^stock/inventory/(?P<pk>[\d]+)/$', views.inventory, name='inventory'),  # noqa
    url(r'^stock/inventory/(?P<pk>[\d]+)/edit/$', views.inventory_update, name='inventory_update'),  # noqa
    url(r'^stock/inventory/(?P<pk>[\d]+)/export/$', views.inventory_export, name='inventory_export'),  # noqa
    url(r'^stock/inventory/(?P<pk>[\d]+)/delete/$', views.inventory_delete, name='inventory_delete'),  # noqa
    url(r'^stock/inventory/new/$', views.inventory_create, name='inventory_create'),  # noqa
    url(r'^stock/item/(?P<pk>[\d]+)/edit/$', views.stockitem_update, name='stockitem_update'),  # noqa
    url(r'^stock/item/(?P<pk>[\d]+)/delete/$', views.stockitem_delete, name='stockitem_delete'),  # noqa
    url(r'^stock/item/new/$', views.stockitem_create, name='stockitem_create'),
    url(r'^stock/item/(?P<item_pk>[\d]+)/new-specimen/$', views.specimen_create, name='specimen_create'),  # noqa
    url(r'^stock/specimen/(?P<pk>[\d]+)/edit/$', views.specimen_update, name='specimen_update'),  # noqa
    url(r'^stock/specimen/(?P<pk>[\d]+)/delete/$', views.specimen_delete, name='specimen_delete'),  # noqa
    url(r'^stock/inventory/specimen/add/(?P<inventory_pk>[\d]+)/(?P<specimen_pk>[\d]+)/$', views.inventoryspecimen_add, name='inventoryspecimen_add'),  # noqa
    url(r'^stock/inventory/specimen/increase/(?P<pk>[\d]+)/$', views.inventoryspecimen_increase, name='inventoryspecimen_increase'),  # noqa
    url(r'^stock/inventory/specimen/decrease/(?P<pk>[\d]+)/$', views.inventoryspecimen_decrease, name='inventoryspecimen_decrease'),  # noqa
    url(r'^stock/inventory/specimen/remove/(?P<inventory_pk>[\d]+)/(?P<specimen_pk>[\d]+)/$', views.inventoryspecimen_remove, name='inventoryspecimen_remove'),  # noqa
    url(r'^stock/inventory/specimen/by-barcode/$', views.inventoryspecimen_bybarcode, name='inventoryspecimen_bybarcode'),  # noqa
    url(r'^loan/$', views.loan, name='loan'),
    url(r'^loan/export/$', views.export_loan, name='export_loan'),
]

ideascube/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.decorators.cache import cache_control, cache_page
from django.views.i18n import javascript_catalog


from . import views

urlpatterns = i18n_patterns(
    url(r'^blog/', include('ideascube.blog.urls', namespace="blog")),
    url(r'^library/', include('ideascube.library.urls', namespace="library")),
    url(r'^search/', include('ideascube.search.urls', namespace="search")),
    url(r'^mediacenter/', include('ideascube.mediacenter.urls',
                                  namespace="mediacenter")),
    url(r'^monitoring/', include('ideascube.monitoring.urls',
                                 namespace="monitoring")),
    url(r'^$', views.index, name='index'),
    url(r'^welcome_staff/$', views.welcome_staff, name='welcome_staff'),
    url(r'^tag/$', views.by_tag, name='by_tag'),
    url(r'^server/', include('ideascube.serveradmin.urls', namespace="server")),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, kwargs={"next_page": "/"},
        name='logout'),
    url(r'^user/$', views.user_list, name='user_list'),
    url(r'^user/(?P<pk>[\d]+)/$', views.user_detail, name='user_detail'),
    url(r'^user/(?P<pk>[\d]+)/edit/$', views.user_update, name='user_update'),
    url(r'^user/(?P<pk>[\d]+)/set-password/$', views.set_password,
        name='user_set_password'),
    url(r'^user/new/$', views.user_create, name='user_create'),
    url(r'^user/export/$', views.user_export, name='user_export'),
    url(r'^user/import/$', views.user_import, name='user_import'),
    url(r'^user/(?P<pk>[\d]+)/delete/$',
        views.user_delete, name='user_delete'),
    url(r'^user/(?P<pk>[\d]+)/toggle-staff/$',
        views.user_toggle_staff, name='user_toggle_staff'),
    url(r'^ajax-proxy/$', cache_page(180)(views.ajax_proxy), name='ajax-proxy')
)
urlpatterns = urlpatterns + [
    url(r'^jsi18n/$', cache_control(max_age=31536000)(javascript_catalog),
        name='jsi18n'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ideascube/monitoring/views.py
from datetime import date, timedelta

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext as _
from django.views.generic import (CreateView, DeleteView, DetailView, FormView,
                                  TemplateView, UpdateView, View)

from ideascube.views import CSVExportMixin
from ideascube.decorators import staff_member_required

from .forms import (EntryForm, ExportEntryForm, ExportLoanForm,
                    InventorySpecimenForm, LoanForm, ReturnForm, SpecimenForm,
                    StockImportForm)
from .models import (Entry, Inventory, InventorySpecimen, Loan, Specimen,
                     StockItem)

user_model = get_user_model()


class EntryView(FormView):
    fields = '__all__'
    template_name = 'monitoring/entry.html'
    form_class = EntryForm
    success_url = reverse_lazy('monitoring:entry')

    def form_valid(self, form):
        count = 0
        module = form.cleaned_data['module']
        activity = form.cleaned_data['activity']
        partner = form.cleaned_data['partner']
        activity_select = form.cleaned_data.get('activity_list')
        if not activity and activity_select:
            activity = activity_select
        for serial in form.cleaned_data['serials']:
            try:
                user = user_model.objects.get(serial=serial)
            except user_model.DoesNotExist:
                msg = _('No user found with serial {serial}')
                msg = msg.format(serial=serial)
                messages.add_message(self.request, messages.ERROR, msg)
            else:
                Entry.objects.create(user=user, module=module,
                                     activity=activity, partner=partner)
                count += 1
        if count:
            msg = _('Created {count} entries')
            msg = msg.format(count=count)
            messages.add_message(self.request, messages.SUCCESS, msg)
        else:
            msg = _('No entry created.')
            messages.add_message(self.request, messages.WARNING, msg)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entries'] = Entry.objects.all()[:50]
        context['export_form'] = ExportEntryForm()
        context['MONITORING_ENTRY_EXPORT_FIELDS'] = settings.MONITORING_ENTRY_EXPORT_FIELDS  # noqa
        return context

entry = staff_member_required(EntryView.as_view())


class ExportEntry(CSVExportMixin, View):
    prefix = 'entry'

    def get(self, *args, **kwargs):
        self.form = ExportEntryForm(self.request.GET)
        if self.form.is_valid():
            return super().get(*args, **kwargs)
        else:
            msg = _('Error while processing entries export')
            messages.add_message(self.request, messages.ERROR, msg)
            messages.add_message()
            return HttpResponseRedirect(reverse_lazy('monitoring:entry'))

    def get_headers(self):
        self.fields = ['module', 'date', 'activity', 'partner']
        self.fields.extend(settings.MONITORING_ENTRY_EXPORT_FIELDS)
        return self.fields

    def get_items(self):
        qs = Entry.objects.order_by('created_at')
        if self.form.cleaned_data['since']:
            qs = qs.filter(created_at__gte=self.form.cleaned_data['since'])
        return qs

    def get_row(self, entry):
        row = {'module': entry.module, 'date': entry.created_at,
               'activity': entry.activity, 'partner': entry.partner}
        for field in settings.MONITORING_ENTRY_EXPORT_FIELDS:
            row[field] = getattr(entry.user, field, None)
        return row

export_entry = staff_member_required(ExportEntry.as_view())


class StockListMixin(object):

    def get_stock(self):
        stock = []
        for key, name in StockItem.MODULES:
            stock.append({
                'key': key,
                'name': name,
                'objects': StockItem.objects.filter(module=key).physical()
            })
        return stock


class Stock(StockListMixin, TemplateView):
    template_name = "monitoring/stock.html"
    model = StockItem

    def get_context_data(self, **kwargs):
        return {
            'stock': self.get_stock(),
            'inventory_list': Inventory.objects.all()
        }
stock = staff_member_required(Stock.as_view())


class InventoryDetail(StockListMixin, DetailView):
    model = Inventory
    template_name = 'monitoring/inventory.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stock'] = self.get_stock()
        context['inventoryspecimen_form'] = InventorySpecimenForm(
            initial={'inventory': self.object})
        return context

inventory = staff_member_required(InventoryDetail.as_view())


class InventoryUpdate(UpdateView):
    model = Inventory
    fields = '__all__'
inventory_update = staff_member_required(InventoryUpdate.as_view())


class InventoryCreate(CreateView):
    model = Inventory
    fields = '__all__'
inventory_create = staff_member_required(InventoryCreate.as_view())


class InventoryDelete(DeleteView):
    model = Inventory
    success_url = reverse_lazy('monitoring:stock')
inventory_delete = staff_member_required(InventoryDelete.as_view())


class InventoryExport(CSVExportMixin, DetailView):
    model = Inventory

    def get(self, *args, **kwargs):
        self.object = self.get_object()
        return super().get(*args, **kwargs)

    def get_headers(self):
        self.headers = ['module', 'name', 'description', 'barcode', 'serial',
                        'count', 'comments', 'status']
        return self.headers

    def get_items(self):
        return Specimen.objects.physical()

    def get_row(self, specimen):
        return {
            'module': specimen.item.module,
            'name': specimen.item.name,
            'description': specimen.item.description,
            'barcode': specimen.barcode,
            'serial': specimen.serial,
            'count': specimen.count,
            'comments': specimen.comments,
            'status': specimen.count if specimen in self.object else 'ko'
        }

    def get_filename(self):
        filename = "_".join([
            'inventory',
            settings.IDEASCUBE_ID,
            str(self.object.made_at)
        ])
        return filename
inventory_export = staff_member_required(InventoryExport.as_view())


class StockItemUpdate(UpdateView):
    model = StockItem
    fields = '__all__'
stockitem_update = staff_member_required(StockItemUpdate.as_view())


class StockItemCreate(CreateView):
    model = StockItem
    fields = '__all__'

    def get_initial(self):
        initial = super().get_initial()
        initial['module'] = self.request.GET.get('module')
        return initial

stockitem_create = staff_member_required(StockItemCreate.as_view())


class StockItemDelete(DeleteView):
    model = StockItem
    success_url = reverse_lazy('monitoring:stock')
stockitem_delete = staff_member_required(StockItemDelete.as_view())


class StockExport(CSVExportMixin, View):
    model = StockItem
    prefix = 'stock'

    def get_headers(self):
        return ['module', 'name', 'description']

    def get_items(self):
        qs = super().get_items()
        qs = qs.filter(book__isnull=True)

        return qs

    def get_row(self, item):
        return {
            'module': item.module, 'name': item.name,
            'description': item.description,
        }
stock_export = staff_member_required(StockExport.as_view())


class StockImport(FormView):
    form_class = StockImportForm
    template_name = 'monitoring/stock_import.html'
    success_url = reverse_lazy('monitoring:stock')

    def form_valid(self, form):
        items, errors = form.save()

        if items:
            messages.success(
                self.request,
                _('Successfully imported {} items').format(len(items)))

        for error in errors:
            messages.error(self.request, error)

        return super().form_valid(form)
stock_import = staff_member_required(StockImport.as_view())


class SpecimenUpdate(UpdateView):
    model = Specimen
    form_class = SpecimenForm
specimen_update = staff_member_required(SpecimenUpdate.as_view())


class SpecimenCreate(CreateView):
    model = Specimen
    form_class = SpecimenForm

    def get_initial(self):
        item = get_object_or_404(StockItem, pk=self.kwargs['item_pk'])
        return {'item': item}
specimen_create = staff_member_required(SpecimenCreate.as_view())


class SpecimenDelete(DeleteView):
    model = Specimen
    success_url = reverse_lazy('monitoring:stock')
specimen_delete = staff_member_required(SpecimenDelete.as_view())


class InventorySpecimenAdd(View):

    def get(self, request, *args, **kwargs):
        inventory = get_object_or_404(Inventory,
                                      pk=self.kwargs['inventory_pk'])
        specimen = get_object_or_404(Specimen, pk=self.kwargs['specimen_pk'])
        InventorySpecimen.objects.get_or_create(
            inventory=inventory, specimen=specimen,
            defaults={'count': specimen.count})
        url = reverse_lazy('monitoring:inventory',
                           kwargs={'pk': self.kwargs['inventory_pk']})
        return HttpResponseRedirect(url)
inventoryspecimen_add = staff_member_required(
    InventorySpecimenAdd.as_view())


class InventorySpecimenByBarCode(FormView):
    form_class = InventorySpecimenForm
    fields = '__all__'

    def redirect(self, form):
        url = reverse_lazy('monitoring:inventory',
                           kwargs={'pk': form.cleaned_data['inventory'].pk})
        return HttpResponseRedirect(url)

    def form_valid(self, form):
        form.save()

ideascube/monitoring/templates/monitoring/entry.html
{% extends 'two-third-third.html' %}

{% load i18n ideascube_tags static %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static "monitoring/monitoring.css" %}">
    {% include 'ideascube/includes/form_statics.html' %}
{% endblock extra_head %}

{% block twothird %}
    <form id="entry_form" method="post">
        {% csrf_token %}
        {{ form.errors }}
        {{ form.serials }}
        <h5>{% trans 'Specific activity (optional)' %}</h5>
        {{ form.activity_list }}
        {{ form.activity }}
        <h5>{% trans 'Partner (optional)' %}</h5>
        {{ form.partner }}
        {{ form.module }}
        <input type="submit" name="entry_cinema" value="{% trans 'To the cinema module' %}" class="cinema" />
        <input type="submit" name="entry_library" value="{% trans 'To the library module' %}" class="library" />
        <input type="submit" name="entry_digital" value="{% trans 'To the digital module' %}" class="digital" />
    </form>
    <hr />
    <table>
        <tr>
            <th>{% trans "Module" %}</th>
            <th>{% trans "Member" %}</th>
            <th>{% trans "When" %}</th>
            {% for field in MONITORING_ENTRY_EXPORT_FIELDS %}
                <th>{{ user|model|field_verbose_name:field }}</th>
            {% endfor %}
        </tr>
        {% for entry in entries %}
        <tr>
            <td><span class="{{ entry.module }} module">{{ entry.module }}</span></td>
            <td>{{ entry.user }}</td>
            <td>{% blocktrans  with time=entry.created_at|timesince %}{{ time }} ago{% endblocktrans%}</td>
            {% for field in MONITORING_ENTRY_EXPORT_FIELDS %}
                <td>{{ entry.user|field_value_display:field|default:'—' }}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
{% endblock twothird %}
{% block third %}
    <div class="card tinted">
        <h4>{% trans 'Export' %}</h4>
        <form method="get" action="{% url 'monitoring:export_entry' %}" id="entry_export_form">
            {{ export_form }}
            <input type="submit" value="{% trans 'Export' %}" />
        </form>
    </div>
{% endblock third %}
{% block extra_foot %}
    <script type="text/javascript">
        ID.focusOn('[name="serials"]');
        ID.initDatepicker('since');
        ID.stopEnterKey('activity');
        ID.stopEnterKey('partner');
    </script>
{% endblock extra_foot %}

ideascube/monitoring/templates/monitoring/inventory.html
{% extends 'two-third-third.html' %}

{% load i18n ideascube_tags monitoring_tags static %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static "monitoring/monitoring.css" %}">
    {% include 'ideascube/includes/form_statics.html' %}
{% endblock extra_head %}

{% block twothird %}
    <h2>{{ inventory.made_at }}</h2>
    <form action="{% url 'monitoring:inventoryspecimen_bybarcode' %}" method="post" id="by_barcode">
        {% csrf_token %}
        {{ inventoryspecimen_form.specimen }}
        {{ inventoryspecimen_form.inventory }}
        {{ inventoryspecimen_form.count }}
    </form>
    {% for module in stock %}
        <table class="stock {{ module.key }}">
            <caption>{% trans module.name %}</caption>
            <tr>
                <th>{% trans 'count' %}</th>
                <th>{% trans 'barcode' %}</th>
                <th>{% trans 'serial number' %}</th>
                <th>{% trans 'status' %}</th>
            </tr>
        {% for item in module.objects  %}
            <tr class="stockitem">
              <td>{% trans 'Total:' %} {{ item.specimens.physical|length }}</td>
              <td colspan="3">{{ item }} <em>{{ item.description|truncatewords:10 }}</em></td>
            </tr>
            {% for specimen in item.specimens.physical %}
                {% get_inventory_specimen inventory specimen as inventoryspecimen %}
                <tr class="specimen">
                    <td>{{ specimen.count }}</td>
                    <td>{{ specimen.barcode|default:'—' }}</td>
                    <td>{{ specimen.serial|default:'—' }}</td>
                    {% if inventoryspecimen %}
                        <td class="{% if inventoryspecimen.count >= specimen.count %}found{% else %}missing{% endif %}">{{ inventoryspecimen.count }} <a href="{% url 'monitoring:inventoryspecimen_increase' pk=inventoryspecimen.pk %}">{% fa "plus-circle" %}</a> <a href="{% url 'monitoring:inventoryspecimen_decrease' pk=inventoryspecimen.pk %}">{% fa "minus-circle" %}</a> <a href="{% url 'monitoring:inventoryspecimen_remove' inventory_pk=inventory.pk specimen_pk=specimen.pk %}">{% fa "times-circle" %}</a></td>
                    {% else %}
                        <td class="notfound"><a href="{% url 'monitoring:inventoryspecimen_add' inventory_pk=inventory.pk specimen_pk=specimen.pk %}">{% fa "check-circle" %}</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        {% empty %}
            <tr><td colspan="3">{% trans 'Stock is empty for this module.' %}</td></tr>
        {% endfor %}
        </table>
        <hr />
    {% endfor %}
{% endblock twothird %}
{% block third %}
    <ul class="card tinted admin">
        <li>{% fa 'pencil' 'fa-fw' %} <a href="{% url 'monitoring:inventory_update' pk=inventory.pk %}">{% trans 'Edit' %}</a></li>
        <li>{% fa 'download' 'fa-fw' %} <a href="{% url 'monitoring:inventory_export' pk=inventory.pk %}">{% trans 'Export in CSV' %}</a></li>
        <li>{% fa 'arrow-right' 'fa-fw' %} <a href="{% url 'monitoring:stock' %}">{% trans 'Manage stock' %}</a></li>
    </ul>
{% endblock third %}


{% block extra_foot %}
    <script type="text/javascript">
        ID.focusOn('[name="specimen"]');
    </script>
{% endblock extra_foot %}

ideascube/monitoring/templates/monitoring/inventory_form.html
{% extends 'form-fullpage.html' %}
{% load i18n %}

{% block heading %}
    {% if inventory %}
        <h2>{% blocktrans with date=inventory.made_at %}Edit inventory from {{ date }}{% endblocktrans %}</h2>
    {% else %}
        <h2>{% trans "Start new inventory" %}</h2>
    {% endif %}
{% endblock heading %}
{% block col %}
    {% if inventory %}
        <a class="button" href="{{ inventory.get_absolute_url }}">{% trans 'cancel' %}</a>
        <a class="button warning" href="{% url 'monitoring:inventory_delete' pk=inventory.pk %}">{% trans 'delete' %}</a>
    {% endif %}
{% endblock col %}

{% block extra_foot %}
    <script type="text/javascript">
        ID.initDatepicker('made_at')
    </script>
{% endblock extra_foot %}

ideascube/monitoring/templates/monitoring/loan.html
{% extends 'two-third-third.html' %}

{% load i18n ideascube_tags static %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static "monitoring/monitoring.css" %}">
    {% include 'ideascube/includes/form_statics.html' %}
{% endblock extra_head %}

{% block twothird %}
    <h2>{% trans "Loan" %}</h2>
    <form method="post" id="loan_form">
        {% csrf_token %}
        {% for field in loan_form %}
            {% form_field field %}
        {% endfor %}
        <input type="submit" name="do_loan" value="{% trans 'Validate' %}">
    </form>
    <hr />
    <h3>{% trans "Ongoing loans" %}</h3>
    <table>
        <tr>
            <th>{% trans "Item" %}</th>
            <th>{% trans "Barcode" %}</th>
            <th>{% trans "Serial number" %}</th>
            <th>{% trans "User" %}</th>
            <th>{% trans "Due date" %}</th>
            <th>{% trans "Comments" %}</th>
            <th>{% trans "By" %}</th>
        </tr>
        {% for loan in loans %}
            <tr>
                <td>{{ loan.specimen.item }}</td>
                <td>{{ loan.specimen.barcode }}</td>
                <td>{{ loan.specimen.serial }}</td>
                <td>{{ loan.user }}</td>
                <td>{% if loan.due %}{% fa 'exclamation' %} {% endif %}{{ loan.due_date }}</td>
                <td>{{ loan.comments }}</td>
                <td>{{ loan.by }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock twothird %}
{% block third %}
    <h3>{% trans "Return" %}</h3>
    <form method="post" id="return_form">
        {% csrf_token %}
        {% for field in return_form %}
            {% form_field field %}
        {% endfor %}
        <input type="submit" name="do_return" value="{% trans 'Validate' %}">
    </form>
    <hr />
    <h3>{% trans "Export" %}</h3>
    <form method="get" id="export_form" action="{% url 'monitoring:export_loan' %}">
        {% csrf_token %}
        {% for field in export_form %}
            {% form_field field %}
        {% endfor %}
        <input type="submit" name="do_export" value="{% trans 'Export' %}">
    </form>
{% endblock third %}

{% block extra_foot %}
    <script type="text/javascript">
        ID.focusOn('[name=specimen]');
        ID.initDatepicker('due_date');
        ID.initDatepicker('since');
        ID.stopEnterKey('specimen');
        ID.stopEnterKey('user');
    </script>
{% endblock extra_foot %}

ideascube/monitoring/templates/monitoring/stock.html
{% extends 'two-third-third.html' %}
{% load i18n ideascube_tags static %}


{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static "monitoring/monitoring.css" %}">
{% endblock extra_head %}

{% block twothird %}
    <h2>{% trans "Stock" %}</h2>
    {% for module in stock %}
        <table class="stock {{ module.key }}">
            <caption>{% trans module.name %} <a href="{% url 'monitoring:stockitem_create' %}?module={{ module.key }}"><i class="fa fa-plus"></i> {% trans "Add stock item" %}</a></caption>
            <tr>
                <th>{% trans 'count' %}</th>
                <th>{% trans 'barcode' %}</th>
                <th>{% trans 'serial number' %}</th>
                <th>{% trans 'Actions' %}</th>
            </tr>
        {% for item in module.objects  %}
            <tr class="stockitem" id="stockitem-{{ item.pk }}">
                <td>{% trans 'Total:' %} {{ item.specimens.physical|length }}</td>
                <td colspan="2">{{ item }} <em>{{ item.description|truncatewords:10 }}</em></td>
                <td class="actions">
                    <a href="{% url 'monitoring:stockitem_update' pk=item.pk %}" title="{% trans 'Edit' %}">
                        {% fa 'pencil-square' %}
                    </a>
                    <a href="{% url 'monitoring:specimen_create' item_pk=item.pk %}" title="{% trans 'Add new specimen of this item' %}">
                        {% fa 'plus-square' %}
                    </a>
                </td>
            </tr>
            {% for specimen in item.specimens.physical %}
                <tr class="specimen">
                    <td>{{ specimen.count }}</td>
                    <td>{{ specimen.barcode|default:'—' }}</td>
                    <td>{{ specimen.serial|default:'—' }}</td>
                    <td class="actions">
                        <a href="{% url 'monitoring:specimen_update' pk=specimen.pk %}" title="{% trans 'Edit this specimen' %}">
                            {% fa 'pencil-square' %}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        {% empty %}
            <tr><td colspan="2">{% trans 'Stock is empty for this module.' %}</td></tr>
        {% endfor %}
        </table>
        <hr />
    {% endfor %}
{% endblock twothird %}
{% block third %}
    <ul class="card tinted admin">
        <li>{% fa 'archive' 'fa-fw' %} <a href="{% url 'monitoring:stockitem_create' %}">{% trans "Add stock item" %}</a></li>
        <li>{% fa 'table' 'fa-fw' %} <a href="{% url 'monitoring:stock_export' %}">{% trans "Export" %}</a></li>
        <li>{% fa 'upload' 'fa-fw' %} <a href="{% url 'monitoring:stock_import' %}">{% trans "Import" %}</a></li>
        <li>{% fa 'bars' 'fa-fw' %} <a href="{% url 'monitoring:inventory_create' %}">{% trans "Start inventory" %}</a></li>
    </ul>
    <div class="card tinted admin">
        <h4>{% trans 'Inventories' %}</h4>
        {% for inventory in inventory_list  %}
            <p><a href="{% url 'monitoring:inventory' pk=inventory.pk %}">{{ inventory.made_at }}</a></p>
        {% empty %}
            <p>{% trans 'No inventory yet.' %} <a href="{% url 'monitoring:inventory_create' %}">{% trans "Start one now" %}.</a></p>
        {% endfor %}
    </div>
{% endblock third %}

ideascube/monitoring/templates/monitoring/stockitem_detail.html
{% extends 'two-third-third.html' %}

{% load i18n ideascube_tags %}

{% block twothird %}
    <h2>{{ stockitem }}</h2>
{% endblock twothird %}
{% block third %}
    <ul class="card tinted admin">
        <li>{% fa 'pencil' 'fa-fw' %} <a href="{% url 'monitoring:stockitem_update' pk=stockitem.pk %}">Edit</a></li>
        <li>{% fa 'plus' 'fa-fw' %} <a href="{% url 'monitoring:specimen_create' item_pk=stockitem.pk %}">Add new specimen of this item</a></li>
    </ul>
{% endblock third %}